export const FETCH_LAYOUT_SUCESS = 'FETCH_LAYOUT_SUCESS';
export const FETCH_LAYOUT_FAILED = 'FETCH_LAYOUT_FAILED';
export const FETCH_MARKETS_SUCESS = 'FETCH_MARKETS_SUCESS';
export const FETCH_MARKETS_FAILED = 'FETCH_MARKETS_FAILED';
export const FETCH_LAYOUT = 'FETCH_LAYOUT';
export const FETCH_MARKETS = 'FETCH_MARKETS';
export const SET_MARKET = 'SET_MARKET';
